name: Simple CI/CD workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install gtest 
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - uses: actions/checkout@v3
    - name: build
      run: cmake -S . -B build && cmake --build build
    - name: test using libgtest and write result to output.txt
      run: cd build && ctest >> ../output.txt
    - name: send notification email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: simplecicd@gmail.com
        password: minhhieu1234
        subject: Github Actions job result
        to: sniper19121998@gmail.com
        from: MinhHieu
        body: Build job of ${{github.repository}} completed successfully! See the result in the attached file!
        html_body: ../output.txt
        ignore_cert: true
        convert_markdown: true
        # Optional attachments:
        attachments: ../output.txt
        priority: low